lib/volt_web/router.ex
defmodule VoltWeb.Router do
  use VoltWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VoltWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker

    plug VoltWeb.Authentication, repo: Volt.Repo

  end

  forward "/sent_emails", Bamboo.SentEmailViewerPlug

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VoltWeb do
    pipe_through :browser

    # resources "/password-reset", PasswordResetController, except: [:index, :show]

    resources "/password-reset", PasswordResetController, except: [:index, :show]

    get "/", PageController, :index
    # resources "/customers", CustomerController, only: [:new, :create, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    # resources "/menus", MenuController
    # resources "/customer_orders", Customer_OrderController
    # resources "/carts", CartController


    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    get "/register", AuthController, :index


    get    "/new-customer",  CustomerController, :new
    post   "/customer",  CustomerController, :create
    get "/customer/edit/:id", CustomerController, :edit
    post "/customer/update/:id", CustomerController, :update
    get "/customer/profile", CustomerProfileController, :index
    get "/restaurants", RestaurantlistsController, :index

    get    "/new-courier",  CourierController, :new
    post   "/courier",  CourierController, :create
    get "/courier/profile", CourierProfileController, :index
    get "/courier/edit/:id", CourierController, :edit
    post "/courier/update/:id", CourierController, :update

    get    "/new-restaurant",  RestaurantController, :new
    post   "/restaurant",  RestaurantController, :create
    get "/restaurant/profile", RestaurantProfileController, :index
    get "/restaurant/edit/:id", RestaurantController, :edit
    post "/restaurant/update/:id", RestaurantController, :update

    get "/restaurant/:id/menu", RestaurantController, :menuIndex
    get "/restaurant/edit/items/:id", RestaurantController, :edit_item
    post "/restaurant/update/item/:id", RestaurantController, :update_item
    delete "/restaurant/delete_item/:id", RestaurantController, :delete_item

    get "/restaurants/:restName", PublicRestaurantController, :index
    get "/restaurants/:restName/choose-address", PublicRestaurantController, :addressIndex
    post "/restaurants/:restName/choose-address", PublicRestaurantController, :process

    get "/restaurant/menu/:id/add-new-item", ItemController, :new
    post "/restaurant/menu/:id/add-new-item", ItemController, :create
    get "/restaurant/menu/:id/items", ItemController, :index

    post "/restaurant/menu/items", CartItemController, :create

    # get "/customer/cart", CartController, :index
    # delete "/customer/cart/:id", CartItemController, :delete

    post "/customer/order/items", OrderController, :create_order
    # get "/customer/orders", OrderController, :index

    get "/restaurant/restaurant-orders", RestaurantController, :ordersIndex
    post "/restaurant/restaurant-orders/:id", RestaurantController, :update_order_time
    post "/restaurant/restaurant-orders/mark-prepared/:id", RestaurantController, :mark_order_prepared

    get "/restaurant/restaurant-orders/show/:id", RestaurantController, :show_order

    post "/restaurant/restaurant-orders/reject/:id", RestaurantController, :reject_order
    post "/restaurant/restaurant-orders/cancel-order/:id", RestaurantController, :cancel_order

    # Courier orders
    get "/courier/available-orders/address-selection", CourierController, :address_selection
    post "/courier/available-orders/address-selection/:id", CourierController, :address_selection_process
    get "/courier/available-orders/current-address=:address", CourierController, :available_orders_index

    post "/courier/available-orders/accept-order/:id", CourierController, :accept_order
    post "/courier/available-orders/reject-order/:id", CourierController, :reject_order

    get "/customer/my-orders", CustomerController, :orders_index
    get "/restaurant/my-orders/history", RestaurantController, :orders_history
    get "/courier/my-orders", CourierController, :orders_index
    post "/courier/complete-order/:id", CourierController, :complete_order

    get "/customer/orders/:id/leave-review", CustomerController, :leave_review_index
    post "/customer/orders/leave-review", CustomerController, :leave_review
  end

  # Other scopes may use custom stacks.
  # scope "/api", VoltWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: VoltWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/volt/accounts/restaurant.ex
defmodule Volt.Accounts.Restaurant do
  use Ecto.Schema
  import Ecto.Changeset
  alias Volt.Menus.Menu
  alias Volt.Orders.Order
  alias Volt.Reviews.Review

  schema "restaurants" do
    field :email, :string
    field :crypted_password, :string
    field :name, :string
    field :address, :string
    field :opens_at, :string
    field :closes_at, :string
    field :likes, :integer
    field :dislikes, :integer
    field :role, :string, default: "Restaurant"
    field :description, :string

    field :category, :string
    field :tags, :string

    field :password_reset_token, :string, default: nil
    field :password_reset_sent_at, :naive_datetime, default: nil
    has_one :menus, Menu
    has_many :orders, Order
    has_many :reviews, Review


    timestamps()
  end

  def changeset(restaurant, attributes) do
    restaurant
    |> cast(attributes, [:category,:tags,:description, :email, :crypted_password, :name, :address, :opens_at, :closes_at, :likes, :dislikes,:password_reset_token, :password_reset_sent_at])
    |> validate_required([:email, :crypted_password, :name, :address, :opens_at, :closes_at])
    |> unique_constraint(:email)
  end

  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["crypted_password"]))
    |> repo.insert()
  end

  defp hashed_password(password) do
    Bcrypt.hash_pwd_salt(password)
  end
end

lib/volt_web/controllers/restaurant_controller.ex
defmodule VoltWeb.RestaurantController do
  use VoltWeb, :controller

  alias Volt.Accounts
  alias Volt.Accounts.Restaurant
  alias Volt.Menus.Menu
  alias Volt.Repo
  alias Volt.Items.Item
  alias Volt.Items
  alias Volt.Orders.Order
  alias Volt.Accounts.Customer

  def new(conn, _params) do
    render conn, "new.html"
  end

  def emailIsUnique(email) do
    repo = Volt.Repo
    noSuchCustomer = is_nil(repo.get_by(Volt.Accounts.Customer, email: email))
    noSuchCourier = is_nil(repo.get_by(Volt.Accounts.Courier, email: email))
    noSuchRestaurant = is_nil(repo.get_by(Volt.Accounts.Restaurant, email: email))

    if(noSuchCustomer && noSuchCourier && noSuchRestaurant) do
      true
    else
      false
    end
  end

  def create(conn, %{"restaurant" => restaurant_params}) do

    closes_at = restaurant_params["closes_at"]
    opens_at = restaurant_params["opens_at"]
    if(correctWorkingTime(opens_at,closes_at)) do
      if(emailIsUnique(restaurant_params["email"])) do
        changeset = Restaurant.changeset(%Restaurant{}, restaurant_params)

        if(address_valid(restaurant_params["address"])) do
          case Restaurant.create(changeset, Volt.Repo) do
            {:ok, _restaurant} ->
              email = to_string(restaurant_params["email"])
              createdRestaurant = Repo.get_by!(Restaurant, email: email)
              menu = %{"restaurant_id" => createdRestaurant.id, "numberOfItems" => 0}
              menChangeset = Menu.changeset(%Menu{}, menu)
              Menu.create(menChangeset, Volt.Repo)
              conn
              |> put_flash(:info, "Restaurant and your menu have been successfully created.")
              |> redirect(to: Routes.session_path(conn,:new))
            {:error, changeset} ->
              conn
              |> put_flash(:info, "Restaurant creation failed.")
              |> render(conn, "new.html", changeset: changeset)
          end
        else
          conn
            |> put_flash(:error, "Your registration has failed: Address doesn't exists or entered in wrong format!")
            |> redirect(to: Routes.restaurant_path(conn,:new))
        end
      else
         conn
         |> put_flash(:error, "Restaurant registration has failed. Entered email exists on system!")
         |> redirect(to: Routes.restaurant_path(conn,:new))
      end
    else
      conn
      |> put_flash(:error, "Closing hours entered in wrong way. Check open and close hours!")
      |> redirect(to: Routes.restaurant_path(conn,:new))
    end
  end


  def edit(conn, %{"id" => id}) do
    restaurant = Repo.get!(Restaurant, id) |> Repo.preload([:orders])
    has_orders = restaurant.orders |> Enum.map(fn x ->
                                        if ((x.initialStatus == "pending" || x.initialStatus == "accepted") && x.orderOverallStatus != "delivered") do
                                          true
                                        end
                                      end)
    if Enum.member?(has_orders, true) do
      conn
      |> put_flash(:error, "You can't update your profile information while having ongoing orders! Please, try again later.")
      |> redirect(to: Routes.restaurant_profile_path(conn, :index))
    else
      changeset = Restaurant.changeset(restaurant, %{})
      render(conn, "edit.html", restaurant: restaurant, changeset: changeset)
    end

  end

  def update(conn, restaurant_params) do
    # restaurant = Repo.get!(Restaurant, conn.assigns.current_user.id)
    restaurant = Repo.get_by!(Restaurant, id: conn.assigns.current_user.id) |> Repo.preload([orders: [:customers, :restaurants, :couriers, order_items: [:items]]])

    orders = restaurant.orders |> Enum.filter(fn x -> x.orderOverallStatus == "delivered" end)
    # throw orders

    changeset = Restaurant.changeset(restaurant, restaurant_params)

    closes_at = restaurant_params["closes_at"]
    opens_at = restaurant_params["opens_at"]
    if(correctWorkingTime(opens_at,closes_at)) do
      if(Volt.Geolocation.address_valid(restaurant_params["address"])) do
        Repo.update(changeset)
        redirect(conn, to: Routes.restaurant_profile_path(conn, :index))
      else
        conn
        |> put_flash(:error, "Profile hasn't been edited. Address doesn't exists or entered in wrong format!")
        |> redirect(to: Routes.restaurant_profile_path(conn, :index))
      end
    else
    conn
    |> put_flash(:error, "Closing hours entered in wrong way. Check open and close hours!")
    |> redirect(to: Routes.restaurant_profile_path(conn, :index))
    end
  end

  def menuIndex(conn, %{"id" => id}) do
    restaurant = Repo.get_by!(Restaurant, id: id) |> Repo.preload([:menus])
    menu = Repo.get_by!(Menu, id: restaurant.menus.id) |> Repo.preload([:items])
    render(conn, "menuIndex.html", restaurant: restaurant, menu: menu)
  end

  def edit_item(conn, _params) do
    item = Repo.get_by!(Item, id: conn.params["id"])
    render conn, "edit_item.html", item: item
  end

  def update_item(conn, _params) do
    item = Repo.get_by!(Item, id: conn.params["id"]) |> Repo.preload([menus: [restaurants: [:orders]]])
    has_ongoing_orders = item.menus.restaurants.orders |> Enum.map(fn x -> if(x.initialStatus != "rejected" && x.orderOverallStatus != "delivered" &&     x.isCancelled == false) do true else false end end)
    if(!(has_ongoing_orders |> Enum.member?(true))) do
      changeset = Item.changeset(item, %{"name" => conn.params["item"]["name"], "category" => conn.params["item"]["category"], "description" => conn.params["item"]["description"], "price" => conn.params["item"]["price"]})
      case Repo.update(changeset) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Successfully updated the item info")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
      {:error, _item} ->
        conn
        |> put_flash(:error, "An error occured while updating. Please be sure that you have entered valid information and try again!")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
      end
    else
      conn
        |> put_flash(:error, "You can't update item information while having an ongoing order! Please try again later.")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
    end
  end

  def delete_item(conn, _params) do
    item = Repo.get_by!(Item, id: conn.params["id"]) |> Repo.preload([menus: [restaurants: [:orders]]])
    has_ongoing_orders = item.menus.restaurants.orders |> Enum.map(fn x -> if(x.initialStatus != "rejected" && x.orderOverallStatus != "delivered" &&     x.isCancelled == false) do true else false end end)
    if(!(has_ongoing_orders |> Enum.member?(true))) do
      case Repo.delete(item) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Successfully deleted the item")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
      {:error, _item} ->
        conn
        |> put_flash(:error, "An error occured while deletion!")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
      end
    else
      conn
        |> put_flash(:error, "You can't delete item while having an ongoing order! Please try again later.")
        |> redirect(to: Routes.restaurant_path(conn, :menuIndex, item.menus.restaurants.id))
    end
  end

  def address_valid(address) do
    [lat,long] = Volt.Geolocation.find_location(address)
    address_valid = address |> String.split(",") |> length() == 3
    lat != nil && long != nil && address_valid
  end

  defp correctWorkingTime(opens_at,closes_at) do
    openTime = opens_at |> String.split(":")
    {openHour,_} = Integer.parse(openTime |> Enum.at(0))
    {openMinute,_} = Integer.parse(openTime |> Enum.at(1))

    closeTime = closes_at |> String.split(":")
    {closeHour,_} = Integer.parse(closeTime |> Enum.at(0))
    {closeMinute,_} = Integer.parse(closeTime |> Enum.at(1))

    openHour < closeHour || closeHour == 0 && closeMinute == 0 || openHour == closeHour && openMinute < closeMinute
  end

  def ordersIndex(conn, _params) do
    restaurant = Repo.get_by!(Restaurant, id: conn.assigns.current_user.id) |> Repo.preload([orders: [:customers, :restaurants, :couriers, order_items: [:items]]])

    current_time  = Time.utc_now() |> Time.add(10800) |> Time.to_iso8601() |> String.split(":")
    cur_Hour = current_time |> Enum.at(0) |> Integer.parse()
    cur_Min = current_time |> Enum.at(1) |> Integer.parse()

    orders = restaurant.orders |> Enum.filter(fn x -> order_made = x.orderTimeMade |> String.split(":")
                                                      order_Hour = order_made  |> Enum.at(0) |> Integer.parse()
                                                      order_Min = order_made  |> Enum.at(1) |> Integer.parse()
                                                      (cur_Hour > order_Hour || (cur_Hour == order_Hour && cur_Min >= order_Min))
                                                      end)

    render conn, "ordersIndex.html", orders: orders
  end

  def update_order_time(conn, _params) do
    order_id = conn.params["id"]
    order = Repo.get_by!(Order, id: order_id)
    approxTime = conn.params["approxTime"]["time"]
    restaurant_id = conn.params["approxTime"]["restaurant_id"]

    scheduled_time = calculateTime(approxTime,restaurant_id,order.restaurantPreparationTime,order.orderTimeMade)

    if(scheduled_time != "Error") do
      estimated_time_to_deliver = Volt.Geolocation.distance(order.addressFrom, order.addressTo) |> Enum.at(1)
      additionalTime = trunc(estimated_time_to_deliver*60) + 60

      prep_time = scheduled_time |> String.split(":")
      {prep_Hours, _} = prep_time |> Enum.at(0) |> Integer.parse()
      {prep_Min, _} = prep_time |> Enum.at(1) |> Integer.parse()
      {_,prep_time} = Time.new(prep_Hours,prep_Min,0,0)

lib/volt_web/views/restaurant_view.ex
defmodule VoltWeb.RestaurantView do
  use VoltWeb, :view
end

lib/volt_web/templates/restaurant/edit.html.eex
<%= form_for @conn, Routes.restaurant_path(@conn, :update, @conn.assigns.current_user.id), fn restaurant -> %>
  <div class="register-container">
    <h2 class="register-heading">Update Restaurant Info</h2>
    <div class="border"></div>
    <div class="form-group">
      <%= label restaurant, :name, class: "control-label" %>
      <%= text_input restaurant, :name, value: "#{@conn.assigns.current_user.name}", class: "form-control", id: "name" %>
    </div>
    <div class="form-group">
      <%= label restaurant, :email, class: "control-label" %>
      <%= email_input restaurant, :email, value: "#{@conn.assigns.current_user.email}", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label restaurant, :address, class: "control-label" %>
      <%= text_input restaurant, :address, value: "#{@conn.assigns.current_user.address}", class: "form-control" %>
    </div>

    <div class="filters">
    <p>Category</p>

    <div class="form-group">
    <div hidden id = "content-for-js"><%= @conn.assigns.current_user.category %>|<%= @conn.assigns.current_user.tags %></div>
    <%= label restaurant, "Burger", class: "control-label" %>

    <%= radio_button restaurant, "category", "Burger",  id: "burger-radio-button", required: "true" %>
    </div>
    <div class="form-group">
    <%= label restaurant, "Pizza", class: "control-label" %>
    <%= radio_button restaurant, "category", "Pizza", id: "pizza-radio-button"%>
    </div>
    <div class="form-group">
    <%= label restaurant, "Sushi", class: "control-label" %>
    <%= radio_button restaurant, "category", "Sushi", id: "sushi-radio-button" %>
    </div>

    <p>Choose tags (one or more)</p>

    <div class="form-group">
    <%= label restaurant, "fast-food", class: "control-label" %>
    <input type="checkbox" id="fast-food-check" >
    </div>
    <div class="form-group">
    <%= label restaurant, "vegan", class: "control-label" %>
    <input type="checkbox" id="vegan-check" >
    </div>
    <div class="form-group">
    <%= label restaurant, "american", class: "control-label" %>
    <input type="checkbox" id="american-check" >
    </div>
    <%= label restaurant, "spicy", class: "control-label" %>
    <input type="checkbox" id="spicy-check" >
    </div>
    <div class="form-group input-div">
    <%= text_input restaurant, "tags", id: "final-tags", placeholder: "Choose tags from options above.", class: "form-control", readonly: "true", required: "required" %>
    </div>
</div>
    <div class="form-group">
      <%= label restaurant, :opens_at, class: "control-label" %>
      <%= time_input restaurant, :opens_at, value: "#{@conn.assigns.current_user.opens_at}", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label restaurant, :closes_at, class: "control-label" %>
      <%= time_input restaurant, :closes_at, value: "#{@conn.assigns.current_user.closes_at}", class: "form-control" %>
    </div>
    <div hidden class="form-group">
      <%= label restaurant, :likes, class: "control-label" %>
      <%= number_input restaurant, :likes, readonly: "readonly", value: "#{@conn.assigns.current_user.likes}", class: "form-control" %>
    </div>
    <div hidden class="form-group">
      <%= label restaurant, :dislikes, class: "control-label" %>
      <%= number_input restaurant, :dislikes, readonly: "readonly", value: "#{@conn.assigns.current_user.dislikes}", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= label restaurant, :role, class: "control-label" %>
      <%= text_input restaurant, :role, value: "Restaurant", readonly: "readonly", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label restaurant, :description, class: "control-label" %>
      <%= text_input restaurant, :description, required: :true, id: "description", value: "#{@conn.assigns.current_user.description}", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= submit "Update information", class: "btn btn-primary", id: "submit_button" %>
    </div>
  </div>


<script>
let information = document.getElementById("content-for-js").innerText
let chosen_category = information.split('|')[0]
let chosen_tags = information.split('|')[1].split(',')
let fast_food = document.getElementById("fast-food-check")
let vegan_check = document.getElementById("vegan-check")
let american_check = document.getElementById("american-check")
let spicy_check = document.getElementById("spicy-check")
let final_input = document.getElementById("final-tags")

update_final_input();

document.getElementById(`${chosen_category.toLowerCase()}-radio-button`).click();
chosen_tags.map(el => {document.getElementById(`${el.toLowerCase()}-check`).click();})

fast_food.addEventListener('click',() => {update_final_input()});
vegan_check.addEventListener('click',() => {update_final_input()});
american_check.addEventListener('click',() => {update_final_input()});
spicy_check.addEventListener('click',() => {update_final_input()});

function update_final_input () {
  let result = []

  fast_food.checked && result.push("fast-food");
  vegan_check.checked && result.push("vegan");
  american_check.checked && result.push("american");
  spicy_check.checked && result.push("spicy");

  final_input.value = result.join(",")
}

</script>

  <style>
  .container {
    max-width: 80rem;
  }
  ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color: grey;
  }
  label {
    color: black;
  }
  input {
    color: black;
  }
  .register-container{
    margin-top: 100px;
  }
  .border {
    width: 70px;
    height: 5px;
    background-color: #ffc000;
    margin-top: -15px;
    margin-bottom: 20px;
  }
  </style>
<% end %>

lib/volt_web/templates/restaurant/edit_item.html.eex
<%= form_for @conn, Routes.restaurant_path(@conn, :update_item, @item.id), [as: :item], fn item -> %>
    <div div class="register-container">
        <h2 class="register-heading">Update Item Info</h2>
        <div class="border"></div>
        <div class="form-group">
            <%= label item, :name, class: "control-label" %>
            <%= text_input item, :name, value: "#{@item.name}", class: "form-control", id: "name" %>
        </div>
        <div class="form-group">
            <%= label item, :description, class: "control-label" %>
            <%= text_input item, :description, value: "#{@item.description}", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label item, :category, class: "control-label" %>
            <%= text_input item, :category, value: "#{@item.category}", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= label item, :price, class: "control-label" %>
            <%= number_input item, :price, step: "0.01", value: "#{@item.price}", class: "form-control" %>
        </div>
        <div class="form-group">
            <%= submit "Update information", class: "btn btn-primary", id: "submit_button" %>
        </div>
    </div>

  <style>
  .container {
    max-width: 80rem;
  }
  ::-webkit-input-placeholder { /* WebKit, Blink, Edge */
    color: grey;
  }
  label {
    color: black;
  }
  input {
    color: black;
  }
  .register-container{
    margin-top: 100px;
  }
  .border {
    width: 70px;
    height: 5px;
    background-color: #ffc000;
    margin-top: -15px;
    margin-bottom: 20px;
  }
  </style>
<% end %>

lib/volt_web/templates/restaurant/menuIndex.html.eex
<%= if @restaurant.menus.numberOfItems == 0  do %>
    <h1>There are not any items in your menu yet!</h1>
    <h2> <%= link "Click here", to: Routes.item_path(@conn, :new, @restaurant.menus.id), id: "add-very-new-item" %> and start to add your items to sell</h2>
<% end %>

<%= if @restaurant.menus.numberOfItems != 0  do %>
    <p><%= link "Add new item", to: Routes.item_path(@conn, :new, @restaurant.menus.id), id: "add-new-item" %></p>
    <table>
        <thead>
            <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Category</th>
            <th>Price</th>
            <th>Actions</th>

            <th></th>
            </tr>
        </thead>
        <tbody>
        <%= for item <- @menu.items do %>
            <tr>
            <td><%= item.name %></td>
            <td><%= item.description %></td>
            <td><%= item.category %></td>
            <td>$<%= item.price %></td>

            <td>
                <span><%= link "Edit", to: Routes.restaurant_path(@conn, :edit_item, item.id), id: "edit-button" %></span>
                <span><%= link "Delete", to: Routes.restaurant_path(@conn, :delete_item, item.id), method: :delete, data: [confirm: "Are you sure?"], id: "delete-button" %></span>
            </td>
            </tr>
        <% end %>
        </tbody>
    </table>

<% end %>

<style>
  .container {
    max-width: 80rem;
  }
</style>

lib/volt_web/templates/restaurant/show_order.html.eex
<div><h2>Order Details<h2></div>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Courier</th>
      <th>Order cost</th>
      <th>Ordered items</th>
      <th>Status</th>
      <th>Estimated Preparation</th>
      <th>Placed time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.customers.name %></td>
      <%= if @order.couriers.id != 1 do %>
        <td><%= @order.couriers.name %></td>
      <% else %>
        <td>Not assigned</td>
      <% end %>
      <td>$<%= @order.restaurantFee %></td>
      <td>
          <%= for order_item <- @order.order_items do %>
            <%= order_item.items.name %> (<%= order_item.quantity %>),
          <% end %>
      </td>
      <td><%= @order.orderRestaurantStatus %></td>
      <%= if @order.restaurantPreparationTime == "no-time" do %>
        <td>Not set yet</td>
      <% else %>
        <td><%= @order.restaurantPreparationTime %></td>
      <% end %>
      <td><%= @order.orderTimeMade %></td>
      <td>
        <%= if (@order.initialStatus == "pending" && @order.orderRestaurantStatus == "pending" && @order.orderOverallStatus == "submitted") do %>
          <%= form_for @conn, Routes.restaurant_path(@conn, :reject_order, @order.id), [as: :reject], fn reject -> %>
            <div hidden class="form-group">
                <%= label reject, "id", class: "control-label" %>
                <%= number_input reject, :id, value: "#{@order.id}", required: :true, id: "id", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label reject, "Reject message", class: "control-label" %>
                <%= text_input reject, :rejectMessage, placeholder: "Reason of order rejection", style: "margin-bottom: -40px;",  id: "rejectMesage", class: "form-control" %>
            </div>
            <div class="form-group" style="margin-top: 28px; margin-bottom: 3px;">
                <%= submit "Reject order", style: "background-color: red; border: none;", id: "order_prepared", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
        <%= if (@order.initialStatus == "accepted" && @order.couriers.id == 1) do %>
          <%= form_for @conn, Routes.restaurant_path(@conn, :cancel_order, @order.id), [as: :cancel], fn cancel -> %>
            <div hidden class="form-group">
                <%= label cancel, "id", class: "control-label" %>
                <%= number_input cancel, :id, value: "#{@order.id}", required: :true, id: "id", class: "form-control" %>
            </div>
            <div class="form-group" style="margin-top: 28px; margin-bottom: 3px;">
                <%= submit "Cancel order", style: "background-color: red; border: none;", id: "order_prepared", class: "btn btn-primary" %>
            </div>
          <% end %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<style>
</style>