lib/volt_web/router.ex
defmodule VoltWeb.Router do
  use VoltWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VoltWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NavigationHistory.Tracker

    plug VoltWeb.Authentication, repo: Volt.Repo

  end

  forward "/sent_emails", Bamboo.SentEmailViewerPlug

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VoltWeb do
    pipe_through :browser

    # resources "/password-reset", PasswordResetController, except: [:index, :show]

    resources "/password-reset", PasswordResetController, except: [:index, :show]

    get "/", PageController, :index
    # resources "/customers", CustomerController, only: [:new, :create, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    # resources "/menus", MenuController
    # resources "/customer_orders", Customer_OrderController
    # resources "/carts", CartController


    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    get "/register", AuthController, :index


    get    "/new-customer",  CustomerController, :new
    post   "/customer",  CustomerController, :create
    get "/customer/edit/:id", CustomerController, :edit
    post "/customer/update/:id", CustomerController, :update
    get "/customer/profile", CustomerProfileController, :index
    get "/restaurants", RestaurantlistsController, :index

    get    "/new-courier",  CourierController, :new
    post   "/courier",  CourierController, :create
    get "/courier/profile", CourierProfileController, :index
    get "/courier/edit/:id", CourierController, :edit
    post "/courier/update/:id", CourierController, :update

    get    "/new-restaurant",  RestaurantController, :new
    post   "/restaurant",  RestaurantController, :create
    get "/restaurant/profile", RestaurantProfileController, :index
    get "/restaurant/edit/:id", RestaurantController, :edit
    post "/restaurant/update/:id", RestaurantController, :update

    get "/restaurant/:id/menu", RestaurantController, :menuIndex
    get "/restaurant/edit/items/:id", RestaurantController, :edit_item
    post "/restaurant/update/item/:id", RestaurantController, :update_item
    delete "/restaurant/delete_item/:id", RestaurantController, :delete_item

    get "/restaurants/:restName", PublicRestaurantController, :index
    get "/restaurants/:restName/choose-address", PublicRestaurantController, :addressIndex
    post "/restaurants/:restName/choose-address", PublicRestaurantController, :process

    get "/restaurant/menu/:id/add-new-item", ItemController, :new
    post "/restaurant/menu/:id/add-new-item", ItemController, :create
    get "/restaurant/menu/:id/items", ItemController, :index

    post "/restaurant/menu/items", CartItemController, :create

    # get "/customer/cart", CartController, :index
    # delete "/customer/cart/:id", CartItemController, :delete

    post "/customer/order/items", OrderController, :create_order
    # get "/customer/orders", OrderController, :index

    get "/restaurant/restaurant-orders", RestaurantController, :ordersIndex
    post "/restaurant/restaurant-orders/:id", RestaurantController, :update_order_time
    post "/restaurant/restaurant-orders/mark-prepared/:id", RestaurantController, :mark_order_prepared

    get "/restaurant/restaurant-orders/show/:id", RestaurantController, :show_order

    post "/restaurant/restaurant-orders/reject/:id", RestaurantController, :reject_order
    post "/restaurant/restaurant-orders/cancel-order/:id", RestaurantController, :cancel_order

    # Courier orders
    get "/courier/available-orders/address-selection", CourierController, :address_selection
    post "/courier/available-orders/address-selection/:id", CourierController, :address_selection_process
    get "/courier/available-orders/current-address=:address", CourierController, :available_orders_index

    post "/courier/available-orders/accept-order/:id", CourierController, :accept_order
    post "/courier/available-orders/reject-order/:id", CourierController, :reject_order

    get "/customer/my-orders", CustomerController, :orders_index
    get "/restaurant/my-orders/history", RestaurantController, :orders_history
    get "/courier/my-orders", CourierController, :orders_index
    post "/courier/complete-order/:id", CourierController, :complete_order

    get "/customer/orders/:id/leave-review", CustomerController, :leave_review_index
    post "/customer/orders/leave-review", CustomerController, :leave_review
  end

  # Other scopes may use custom stacks.
  # scope "/api", VoltWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: VoltWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/volt_web/controllers/public_restaurant_controller.ex
defmodule VoltWeb.PublicRestaurantController do
  use VoltWeb, :controller

  alias Erl2ex.Pipeline.Parse
  alias Volt.Items.Item
  alias Volt.Accounts
  alias Volt.Accounts.Customer
  alias Volt.Accounts.Restaurant
  alias Volt.Menus.Menu
  alias Volt.Repo
  alias Volt.Items

  def index(conn, params) do #%{"restName" => id}
    id = params["restName"]
    chosen_address = params["chosen_address"]

    restaurant = Repo.get_by!(Restaurant, id: id) |> Repo.preload([:menus, :reviews])
    menu = Repo.get_by!(Menu, id: restaurant.menus.id) |> Repo.preload([:items])

    items_ID = menu.items |> Enum.map(fn x -> x.id end) |> Enum.join(",")
    courier_fee = Volt.Geolocation.calculate_fee(restaurant.address, chosen_address)
    render(conn, "index.html", restaurant: restaurant, menu: menu, items_ID: items_ID, courier_fee: courier_fee, chosen_address: chosen_address)
    # render(conn, "index.html", restaurant_id: id, chosen_address: address)
  end

  def process(conn, _) do
    params = conn.params["session"]
    id = params["restaurant_id"]
    address = params["input_value"]

    if(address == "" || !Volt.Geolocation.address_valid_soft(address)) do
      conn
      |> put_flash(:error, "Error Occured! Check your entered address.")
      |> redirect(to: Routes.public_restaurant_path(conn, :addressIndex, id))
    else
      conn
      |> redirect(to: Routes.public_restaurant_path(conn,:index, id, chosen_address: address))
    end
  end

  def addressIndex(conn, %{"restName" => id}) do
    customer_id = conn.assigns.current_user.id
    customer = Repo.get_by!(Customer, id: conn.assigns.current_user.id) |> Repo.preload([:orders])
    no_pending_orders = customer.orders|> Enum.filter(fn x -> (x.initialStatus != "rejected" && x.isCancelled == false && x.orderOverallStatus != "delivered") end) |> Enum.empty?()
    if(no_pending_orders) do
      render(conn, "address_selection.html", restaurant_id: id)
    else
      conn
      |> put_flash(:error, "You have an existing order. Please, finish it first.")
      |> redirect(to: Routes.restaurantlists_path(conn, :index))
    end
  end

end

lib/volt_web/views/public_restaurant_view.ex
defmodule VoltWeb.PublicRestaurantView do
  use VoltWeb, :view
end

lib/volt_web/templates/public_restaurant/address_selection.html.eex
<%= form_for @conn, Routes.public_restaurant_path(@conn, :process, @restaurant_id), [as: :session],  fn session -> %>
<h1>Choose address for order!</h1>

    <div hidden class="form-group">
        <%= text_input session, "restaurant_id", id: "restaurant_id", readonly: "readonly", class: "form-control", value: @restaurant_id %>
    </div>

    <div id="content-for-js" hidden><%= @conn.assigns.current_user.address %></div>


    <div style="display: flex; column-gap: 90px;">
        <div style="display: block">
        <div class="border"></div>
            <div class="filters">
                <div class="form-group">
                <%= label session, "Saved Address", class: "control-label" %>
                <%= radio_button session, "address_option", "Living Address",  id: "profile-radio-button", required: "true" %>
                </div>
                <div class="form-group">
                <%= label session, "Current Location", class: "control-label" %>
                <%= radio_button session, "address_option", "Current Location", id: "current-radio-button"%>
                </div>
                <div class="form-group">
                <%= label session, "Enter address", class: "control-label" %>
                <%= radio_button session, "address_option", "Searched Address", id: "custom-radio-button" %>
                </div>
                <div class="form-group input-div">
                <%= text_input session, "input_value", id: "final_address", placeholder: "Ex: Narva mnt 25, 51009, Tartu", class: "form-control", readonly: "true", required: "required" %>
                </div>
            </div>
        </div>
    </div>
  <div class="form-group">
      <%= submit "Go to Menu", class: "btn btn-primary", id: "submit_button" %>
  </div>
<% end %>

<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false&key=API-KEY"></script>

<script>
    var input_field = document.getElementById('final_address');
    var current_radio_button = document.getElementById('current-radio-button');
    var profile_radio_button = document.getElementById('profile-radio-button');
    var custom_radio_button = document.getElementById('custom-radio-button');
    let geoText = '';
    current_radio_button.addEventListener('click', () => {
    input_field.setAttribute('readonly', 'true');
        getLocation();
        setTimeout(getReverseGeocodingData,1000);
    });
    profile_radio_button.addEventListener('click', () => {
        input_field.placeholder = "Ex: Narva mnt 25, 51009, Tartu";
        input_field.setAttribute('readonly', 'true');
        getProfileAddress();
    });
    custom_radio_button.addEventListener('click', () => {
        input_field.placeholder = "Ex: Narva mnt 25, 51009, Tartu";
        input_field.removeAttribute('readonly');
        input_field.value = '';
    });

    function getReverseGeocodingData() {
        let [lat,lng] = geoText.split(',')
        var latlng = new google.maps.LatLng(lat, lng);
        // This is making the Geocode request
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({ 'latLng': latlng }, function (results, status) {
            if (status !== google.maps.GeocoderStatus.OK) {
                input_field.placeholder = "Something went wrong."
                input_field.value = ""
            }
            // This is checking to see if the Geoeode Status is OK before proceeding
            if (status == google.maps.GeocoderStatus.OK) {
                console.log(results);
                var address = (results[0].formatted_address);
                geoText = address
                input_field.value = address
            }
        });
    }

    function getProfileAddress() {
    let address = document.getElementById('content-for-js').innerText;
    input_field.value = address;
    }
    function getLocation() {
    if (geoText == '') {
        if (navigator.geolocation) {
        navigator.geolocation.watchPosition(showPosition, noPosition);
        navigator.geolocation.clearWatch(showPosition, noPosition);
        } else {
        input_field.value = 'Geolocation is not supported by this browser.';
        }
    } else {
        input_field.value = geoText;
    }
    }
    function showPosition(position) {
    if (current_radio_button.checked && geoText == '') {
        geoText = position.coords.latitude + ',' + position.coords.longitude;
        input_field.value = "";
        input_field.placeholder = "Loading...";
    }
    }
    function noPosition(position) {
    if (current_radio_button.checked && geoText == '') {
        input_field.value = 'Geolocation not found.';
    }
    }
</script>

lib/volt_web/templates/public_restaurant/index.html.eex
<span> Restaurant: </span>
<%= @restaurant.name %>
<br/>
<br/>
<br/>

<table>
  <thead>
    <tr>
      <th hidden>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
<div id="content-for-js" hidden><%= @items_ID %>|<%= @courier_fee %></div>
<%= form_for @conn, Routes.order_path(@conn, :create_order), [as: :items],  fn items -> %>
  <%= for item <- @menu.items do %>
    <tr>
      <td hidden><%= text_input items, "item_id-#{item.id}", id: "item-id", value: "#{item.id}", readonly: "readonly", class: "form-control"%></td>
      <td><%= text_input items, "item_name-#{item.id}", id: "item-name", value: "#{item.name}", readonly: "readonly", class: "form-control"%></td>
      <td><%= text_input items, "item_description-#{item.id}", id: "item-description", value: "#{item.description}", readonly: "readonly", class: "form-control"%></td>
      <td><%= text_input items, "item_category-#{item.id}", id: "item-category", value: "#{item.category}", readonly: "readonly", class: "form-control" %></td>
      <td><%= text_input items, "item_price-#{item.id}", id: "item-price-#{item.id}", value: "#{item.price}", readonly: "readonly", class: "form-control"%></td>
      <td><%= number_input items, "item-amount-#{item.id}", id: "amount-#{item.id}", value: "0", min: "0", required: "required", style: "width: 3em; background-color: grey; color: white;", class: "form-control item-amount" %></td>
      <td><%= text_input items, "item-total-#{item.id}", id: "item-total-#{item.id}", value: "0", readonly: "readonly", class: "form-control"%></td>
    </tr>
  <% end %>
  <thead>
    <tr>
      <th>Total Food Price</th>
      <th>Courier Fee</th>
      <th>Final Order Price</th>
    </tr>
    <tr>
      <td><%= text_input items, "item-total-all", id: "item-total-all", value: "0", readonly: "readonly", class: "form-control" %></td>
      <td><%= text_input items, "item-courier-fee", id: "courier-fee", value: "0", readonly: "readonly", class: "form-control" %></td>
      <td><%= text_input items, "item-final-fee", id: "final-fee", value: "0", readonly: "readonly", class: "form-control" %></td>
    </tr>
  </thead>
  </table>

<div>
    <div class="form-group" hidden>
      <%= text_input items, "customer_id", id: "customer_id", value: "#{@conn.assigns.current_user.id}", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "restaurant_id", id: "restaurant_id", value: "#{@restaurant.id}", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "courier_id", id: "courier_id", value: "1", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "restaurantFee", id: "restaurantFee", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "deliveryFee", id: "deliveryFee", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "addressFrom", id: "addressFrom", readonly: "readonly", class: "form-control", value: "#{@restaurant.address}" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "open_time", id: "open_time", readonly: "readonly", class: "form-control", value: "#{@restaurant.opens_at}" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "close_time", id: "close_time", readonly: "readonly", class: "form-control", value: "#{@restaurant.closes_at}" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "addressTo", id: "addressTo", readonly: "readonly", class: "form-control", value: "#{@chosen_address}" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "initialStatus", id: "initialStatus", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "isCancelled", id: "isCancelled", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "orderOverallStatus", id: "orderOverallStatus", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "orderRestaurantStatus", id: "orderRestaurantStatus", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "restaurantPreparationTime", id: "restaurantPreparationTime", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "deliveryTime", id: "deliveryTime", readonly: "readonly", class: "form-control" %>
    </div>
    <div class="form-group" hidden>
      <%= text_input items, "orderTimeMade", id: "orderTimeMade", readonly: "readonly", class: "form-control" %>
    </div>
</div>

    <%= label items, "Schedule Order", class: "control-label" %>
    <div class="form-group">
      <%= label items, "No", class: "control-label", style: "display: inline-flex;padding: 5px;"%>
      <%= radio_button items, "isScheduled", false , id: "schedule-no-radio", style: "margin-right: 20px;", checked: "checked" %>
      <%= label items, "Yes", class: "control-label", style: "display: inline-flex;padding: 5px;" %>
      <%= radio_button items, "isScheduled", true ,  id: "schedule-yes-radio", required: "true" %>
    </div>
    <div class="form-group">
    <div id = "time-input_section" hidden = "true">
      <div class="form-group">
        <%= label items, "scheduled_time", class: "control-label" %>
        <%= time_select items, "scheduled_time", disabled: "true" %>
      </div>
    </div>

    </div>
    <div hidden class="form-group">
      <%= text_input items, "rejectMessage", id: "rejectMessage", readonly: "readonly", class: "form-control" %>
    </div>

  <div class="form-group">
      <p>In case of placing order, money will be withdrawn from this card:</p>
      <%= text_input items, "cardnumber", id: "cardnumber", value: "#{@conn.assigns.current_user.cardnumber}" ,readonly: "readonly", class: "form-control", disabled: "true" %>
  </div>
  <div class="form-group">
      <%= submit "Place your order", class: "btn btn-primary", id: "submit_button" %>
  </div>
<% end %>
  </tbody>

<div class="reviews">
  <%= if @restaurant.reviews != nil do %>
    <h3>Reviews from our customers</h3>
    <%= for review <- @restaurant.reviews do %>
      <div class="single-review">
        <p>Rating: <%= review.rating %> out of 5</p>
        <p>Review: <%= review.body %> </p>
      </div>
    <% end %>
  <% end %>
</div>


<script>
  let information = document.getElementById('content-for-js').innerText.split('|')
  let schedule_yes = document.getElementById('schedule-yes-radio')
  let schedule_no = document.getElementById('schedule-no-radio')
  let disabled_time_input = [document.getElementById('items_scheduled_time_hour'),document.getElementById('items_scheduled_time_minute')]
  let time_input_section = document.getElementById("time-input_section")
  let orderTimeMade = document.getElementById("orderTimeMade")

  let items = information[0].split(',')
  let totals = items.map(el =>`item-total-${el}`)

  let courier_fee = parseFloat(information[1]) //courier-fee
  var currentdate = new Date();
  var datetime = currentdate.getHours() + ":" + currentdate.getMinutes();

  document.getElementById('courier-fee').value = information[1] //courier-fee
  document.getElementById('deliveryFee').value = information[1] //courier-fee
  document.getElementById('restaurantFee').value = 0;
  document.getElementById('final-fee').value = information[1]
  orderTimeMade.value = chooseTime(disabled_time_input[0].value,disabled_time_input[1].value,datetime)



  for(let itr = 0; itr < items.length; itr++) {
    document.getElementById(`amount-${items[itr]}`).addEventListener('change', () => {updateFields(items[itr])});
    updateFields(items[itr])
  }

  schedule_yes.addEventListener('click', () => {
    time_input_section.removeAttribute("hidden");
    disabled_time_input[0].removeAttribute("disabled");
    disabled_time_input[1].removeAttribute("disabled");

    orderTimeMade.value = chooseTime(disabled_time_input[0].value,disabled_time_input[1].value,datetime)
  })
  schedule_no.addEventListener('click', () => {
    time_input_section.setAttribute("hidden","true");
    disabled_time_input[0].setAttribute("disabled","true");
    disabled_time_input[1].setAttribute("disabled","true");

    orderTimeMade.value = chooseTime(disabled_time_input[0].value,disabled_time_input[1].value,datetime)
  })

  disabled_time_input[0].addEventListener('click', () => {
    orderTimeMade.value = chooseTime(disabled_time_input[0].value,disabled_time_input[1].value,datetime)
  })
  disabled_time_input[1].addEventListener('click', () => {
    orderTimeMade.value = chooseTime(disabled_time_input[0].value,disabled_time_input[1].value,datetime)
  })

  function chooseTime(h,m,cur) {
    var formattedNumber = ("0" + h).slice(-2) + ":" + ("0" + m).slice(-2);
    return (schedule_yes.checked) ?  formattedNumber : cur
  }

  function updateFields (item_name) {
    let current_price = document.getElementById(`item-price-${item_name}`).value;
    let current_amount = document.getElementById(`amount-${item_name}`).value;
    console.log(current_amount)
    let total_item_price = document.getElementById(`item-total-${item_name}`).value;
    document.getElementById(`item-total-${item_name}`).value = current_amount * current_price;
    total_for_items = totals.map(x => document.getElementById(x).value).reduce((prev,cur) => parseFloat(prev) + parseFloat(cur),0);
    total_order_price = total_for_items + courier_fee;
    document.getElementById('item-total-all').value = Math.round((total_for_items + Number.EPSILON) * 100) / 100;
    document.getElementById(`restaurantFee`).value = Math.round((total_for_items + Number.EPSILON) * 100) / 100;
    document.getElementById('final-fee').value = Math.round((total_order_price + Number.EPSILON) * 100) / 100;
  }
</script>


<style>
  input[type=number]::-webkit-inner-spin-button {
    opacity: 1;
  }
  input {
    color: black;
    font-size: 20px;
  }

  .reviews {
    margin-top: 50px;
    margin-bottom: 100px;
  }

  .single-review {
    box-shadow: 0 3px 8px 0 rgba(0, 0, 0, .1), 0 4px 11px 0 rgba(0, 0, 0, .08);
    padding: 10px;
    margin: 10px;
    border-radius: 10px;
  }
</style>